# -*- coding: utf-8 -*-
"""récupération_data_PFE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-IMfrOoeUL94ZM8Ldl7ZvD883LyQdeKS
"""

pip install rdflib SPARQLWrapper requests

# --- INSTALLATION DES LIBRAIRIES (A lancer une fois si besoin) ---
!pip install rdflib SPARQLWrapper networkx matplotlib requests

import rdflib
from rdflib import Graph, Literal, URIRef, Namespace
from rdflib.namespace import RDF, RDFS, SKOS, XSD
from SPARQLWrapper import SPARQLWrapper, JSON
import networkx as nx
import matplotlib.pyplot as plt
import requests

# CONFIGURATION
molecules = [
    {"name": "Aspirine", "wd": "Q18216", "pubchem": "2244", "chebi": "15365"},
    {"name": "Paracetamol", "wd": "Q57055", "pubchem": "1983", "chebi": "46195"},
    {"name": "Ibuprofene", "wd": "Q186969", "pubchem": "3672", "chebi": "5855"},
    {"name": "Metformine", "wd": "Q19482", "pubchem": "4091", "chebi": "6801"},
    {"name": "Atorvastatine", "wd": "Q67060", "pubchem": "60823", "chebi": "39548"}
]

# Namespaces
WD = Namespace("http://www.wikidata.org/entity/")
CHEBI = Namespace("http://purl.obolibrary.org/obo/CHEBI_")
PC = Namespace("http://rdf.ncbi.nlm.nih.gov/pubchem/compound/")

# (Visualisation & Stats)

def analyser_graphe(graphe, nom_source):
    """Affiche des stats textuelles sur le graphe récupéré."""
    nb_triplets = len(graphe)
    nb_labels = 0
    nb_synonymes = 0

    for s, p, o in graphe:
        if p == RDFS.label: nb_labels += 1
        if p == SKOS.altLabel: nb_synonymes += 1

    print(f" ANALYSE {nom_source.upper()} :")
    print(f"   - Triplets totaux : {nb_triplets}")
    print(f"   - Labels principaux : {nb_labels}")
    print(f"   - Synonymes (altLabel) : {nb_synonymes}")
    print("-" * 40)

def visualiser_graphe(graph_rdf, titre="Graphe"):
    """Dessine le graphe RDF avec NetworkX."""
    if len(graph_rdf) == 0:
        print(f"Le graphe {titre} est vide, rien à afficher.")
        return

    nx_graph = nx.DiGraph()

    for s, p, o in graph_rdf:
        # On raccourcit les labels pour que le dessin soit lisible
        s_lbl = str(s).split("/")[-1].replace("CHEBI_", "CHEBI:")
        o_lbl = str(o).split("/")[-1]
        if isinstance(o, Literal):
            o_lbl = str(o)[:15] + "..." if len(str(o)) > 15 else str(o) # Tronquer les textes longs

        p_lbl = str(p).split("#")[-1] if "#" in str(p) else str(p).split("/")[-1]

        nx_graph.add_edge(s_lbl, o_lbl, label=p_lbl)

    plt.figure(figsize=(10, 6))
    pos = nx.spring_layout(nx_graph, k=0.6, iterations=50)

    # Dessin
    nx.draw(nx_graph, pos, with_labels=True,
            node_color='#A0CBE2', node_size=2500,
            font_size=9, font_weight="bold", arrows=True, connectionstyle='arc3, rad = 0.1')

    edge_labels = nx.get_edge_attributes(nx_graph, 'label')
    nx.draw_networkx_edge_labels(nx_graph, pos, edge_labels=edge_labels, font_size=8)

    plt.title(titre)
    plt.axis('off')
    plt.show()

# ==========================================
# CORRECTION WIKIDATA (Avec User-Agent)
# ==========================================
import sys

print("\n🔍 ÉTAPE 1 : RÉCUPÉRATION WIKIDATA...")
g_wd = Graph()

# 1. On définit l'agent (OBLIGATOIRE pour ne pas être bloqué)
user_agent = "Projet_PFE_Servier_ECE/1.0 (contact@ece.fr) python-sparqlwrapper"
sparql = SPARQLWrapper("https://query.wikidata.org/sparql", agent=user_agent)

ids_wd = " ".join([f"wd:{m['wd']}" for m in molecules])

query = f"""
SELECT ?entity ?label ?altLabel WHERE {{
  VALUES ?entity {{ {ids_wd} }}

  # On récupère le label principal
  ?entity rdfs:label ?label .
  FILTER(LANG(?label) = "fr")

  # On récupère les synonymes (Optionnel)
  OPTIONAL {{
    ?entity skos:altLabel ?altLabel .
    FILTER(LANG(?altLabel) = "fr")
  }}
}}
"""

sparql.setQuery(query)
sparql.setReturnFormat(JSON)
# On augmente le temps d'attente autorisé avant erreur (timeout)
sparql.setTimeout(60)

try:
    results = sparql.query().convert()

    # Vérification : A-t-on reçu des résultats ?
    bindings = results["results"]["bindings"]
    print(f"   -> {len(bindings)} lignes de données reçues.")

    if len(bindings) == 0:
        print("⚠️ ATTENTION : Wikidata a répondu 0 résultat. Vérifiez les IDs.")

    for res in bindings:
        uri = URIRef(res["entity"]["value"])
        if "label" in res:
            g_wd.add((uri, RDFS.label, Literal(res["label"]["value"], lang="fr")))
        if "altLabel" in res:
            g_wd.add((uri, SKOS.altLabel, Literal(res["altLabel"]["value"], lang="fr")))

    # Sauvegarde
    g_wd.serialize("source_wikidata.ttl", format="turtle")
    print("✅ Fichier 'source_wikidata.ttl' généré avec succès.")

except Exception as e:
    print(f"❌ ERREUR CRITIQUE WIKIDATA : {e}")
    # Si ça plante, on ne crée pas de fichier corrompu

# 2. GÉNÉRATION PUBCHEM (Technique / Base de données)
print("\n🧪 ÉTAPE 2 : GÉNÉRATION PUBCHEM (Technique)...")
g_pc = Graph()

for mol in molecules:
    uri = PC[f"CID{mol['pubchem']}"]
    g_pc.add((uri, RDF.type, URIRef("http://semanticscience.org/resource/ChemicalCompound")))
    g_pc.add((uri, RDFS.label, Literal(f"Compound CID {mol['pubchem']}"))) # Nom technique
    g_pc.add((uri, URIRef("http://example.org/id"), Literal(mol['pubchem'])))

analyser_graphe(g_pc, "PubChem")
visualiser_graphe(g_pc, "Fragment PubChem (Identifiants Techniques)")
g_pc.serialize("source_pubchem.ttl", format="turtle")

# 3. GÉNÉRATION CHEBI (Scientifique / Ontologie)
print("\n ÉTAPE 3 : GÉNÉRATION CHEBI (Scientifique)...")
g_chebi = Graph()

for mol in molecules:
    uri = CHEBI[mol['chebi']]
    g_chebi.add((uri, RDF.type, URIRef("http://purl.obolibrary.org/obo/CHEBI_24431")))
    g_chebi.add((uri, RDFS.label, Literal(mol['name'], lang="en"))) # Souvent en Anglais dans ChEBI
    g_chebi.add((uri, URIRef("http://purl.org/dc/elements/1.1/identifier"), Literal(f"CHEBI:{mol['chebi']}")))

analyser_graphe(g_chebi, "ChEBI")
visualiser_graphe(g_chebi, "Fragment ChEBI (Ontologie Scientifique)")
g_chebi.serialize("source_chebi.ttl", format="turtle")

print("\n TERMINÉ : Les 3 fichiers .ttl sont prêts pour GraphDB.")